version: "3.9"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      postgres_db:
        condition: service_healthy
  postgres_db:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ipl
      POSTGRES_DB: exoplanets
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3


volumes:
  postgres_data:

